### ISSUE TITLE
Стиль названия методов

### ISSUE THREAD

**Issue by SuhEugene** [Andrmist/spk_api#1]
В JS обычно используют camelCase для названия методов функций, а не snake_case, как в питоне
Моё предложение исправления:
- Переименовать snake_case функции в camelCase
- Создать алиасы функций в snake_case стиле
- Пометить snake_case как deprecated

**Comment by Andrmist** [comment]
Поправил, полностью поправлю после обновления API на сайте https://spk.jakksoft.com
